### ISSUE TITLE
Adding the latest versions

### ISSUE THREAD

**Issue by moodmosaic** [masonicboom/btcrpcapi#7]
@masonicboom, if I just run `make`, will I get those latest versions that are missing or do I need to do manual work?

* 0.18.0
* 0.18.1,
* 0.19.0.1
* 0.19.1
* 0.20.0
* 0.20.1
* 0.21.0

Just let me know and I may be able to help.

---

Version history: https://bitcoin.org/en/version-history

**Comment by moodmosaic** [comment]
It looks like first I had to clone bitcoin into the root dir and then run `make all`. By the way, it seems like this parsers won't work with the recent versions of bitcoin (I guess because of breaking changes or files/functions moved).

**Comment by stevenroose** [comment]
I'd be interested in a hosted version with the new versions. Why did you cc me?

**Comment by moodmosaic** [comment]
@stevenroose, IIRC, because you've contributed to the project. From what I've seen on my local, the current parser(s) will work up to version 0.18, and after that it seems all broken (breaking changes in file/API structure?)
